package fr.formation.afpa.domain;
// Generated 23 mai 2021 13:43:00 by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * CodingLanguage generated by hbm2java
 */
@Entity
@Table(name = "coding_language", catalog = "SAJ")
public class CodingLanguage implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<UserProfile> users = new HashSet<UserProfile>(0);
//	private Set<LanguageLibrary> languageLibraries = new HashSet<LanguageLibrary>(0);

	public CodingLanguage() {
	}

	public CodingLanguage(String name, Set<UserProfile> users) {
		this.name = name;
		this.users = users;
		// this.languageLibraries = languageLibraries;
	}

	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_has_coding_language", catalog = "SAJ", joinColumns = {
			@JoinColumn(name = "coding_language_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "interven_id", nullable = false, updatable = false) })
	public Set<UserProfile> getUsers() {
		return users;
	}

	public void setUsers(Set<UserProfile> users) {
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "codingLanguage")
//	public Set<LanguageLibrary> getLanguageLibraries() {
//		return this.languageLibraries;
//	}
//
//	public void setLanguageLibraries(Set<LanguageLibrary> languageLibraries) {
//		this.languageLibraries = languageLibraries;
//	}

	@Override
	public String toString() {
		return "CodingLanguage [id=" + id + ", name=" + name;
	}

}
