package fr.formation.afpa.domain;
// Generated 23 mai 2021 13:43:00 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LanguageLibrary generated by hbm2java
 */
@Entity
@Table(name = "language_library", catalog = "SAJ")
public class LanguageLibrary implements java.io.Serializable {


	private int id;
	//private CodingLanguage codingLanguage;
	private String nom;
	private Set<Tickets> ticketses = new HashSet<Tickets>(0);
	private Set<Tickets> tickets = new HashSet<Tickets>(0);

	public LanguageLibrary() {
	}
	public LanguageLibrary(String nom) {
		this.nom = nom;

	}
	public LanguageLibrary(int id, String nom) {
		this.id = id;
		this.nom = nom;
	//	this.codingLanguage = codingLanguage;
	}

	public LanguageLibrary(int id, String nom, Set<Tickets> ticketses, Set<Tickets> tickets) {
		this.id = id;
	//	this.codingLanguage = codingLanguage;
		this.nom = nom;
		this.ticketses = ticketses;
		this.tickets = tickets;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "coding_language_id", nullable = false)
//	public CodingLanguage getCodingLanguage() {
//		return this.codingLanguage;
//	}
//
//	public void setCodingLanguage(CodingLanguage codingLanguage) {
//		this.codingLanguage = codingLanguage;
//	}

	@Column(name = "nom",unique = true, length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "languageLibrary")
	public Set<Tickets> getTicketses() {
		return this.ticketses;
	}

	public void setTicketses(Set<Tickets> ticketses) {
		this.ticketses = ticketses;
	}
	
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ticket_has_tag", catalog = "SAJ", joinColumns = {
			@JoinColumn(name = "id_tag", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_ticket", nullable = false, updatable = false) })
	public Set<Tickets> getTickets() {
		return tickets;
	}

	public void setTickets(Set<Tickets> tickets) {
		this.tickets = tickets;
	}

	@Override
	public String toString() {
		return "LanguageLibrary [id=" + id + ", nom=" + nom + "]";
	}

}
