package fr.formation.afpa.domain;
// Generated 23 mai 2021 13:43:00 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "SAJ")
public class Message implements java.io.Serializable {

	private Integer id;
	private String text;
	private Date dateMsg;
	private Set<UserProfile> users = new HashSet<UserProfile>(0);

	public Message() {
	}

	public Message(String text, Date dateMsg, Set<UserProfile> users) {
		this.text = text;
		this.dateMsg = dateMsg;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Text")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateMsg", length = 10)
	public Date getDateMsg() {
		return this.dateMsg;
	}

	public void setDateMsg(Date dateMsg) {
		this.dateMsg = dateMsg;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "message_has_user", catalog = "SAJ", joinColumns = {
			@JoinColumn(name = "message_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "user_ID", nullable = false, updatable = false) })
	public Set<UserProfile> getUsers() {
		return this.users;
	}

	public void setUsers(Set<UserProfile> users) {
		this.users = users;
	}

}
